apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iucg1bwor-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iucg1bwor-dotnet-basic-gitops